# Generated by Django 6.0.3 on 2026-03-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
    ]
